# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Datascience Bolgs
# Description of the Site
description: Blogs on Machine Learning, Deep Learning , NLP , Computer Vision
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: http://www.letustweak.com/wp-content/uploads/2016/10/data-science-word-cloud-720x340.jpg
# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: kellasaikumar123@gmail.com
facebook_username: saikumar.kella.3
twitter_username: SaikumarKella
instagram_username: 
linkedin_username: sai-kumar-kella-a76882134
github_username:  saikumarkella
youtube_channel_id: 
reddit_username: 
behance_username: 
dribbble_username: 
spotify_username: 

# Google Analytics
google-analytics: UA-163806439-1

# Disqus
disqus-shortname: saikella

# Name of the Author
author-name: Saikumarkella
# URL for the Image of the Author
author-image: https://github.com/saikumarkella/saikumarkella.github.io/blob/main/sai.JPG
# 60 Words About the Author
author-about: I am Undergraduate sutdent from Acharaya Nagarjuna university.I am data science entusiast with hands on over many machine learning alogothms.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/saikumarkella

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
